import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#94A3B8",
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#456491",
    marginBottom: 20,
    marginTop: 10,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1B365D",
    marginBottom: 10,
  },
  label: {
    fontSize: 14,
    fontWeight: "500",
    color: "#1B365D",
    marginBottom: 6,
  },
  formGroup: {
    marginBottom: 15,
  },
  input: {
    backgroundColor: "#f8efd8",
    borderWidth: 1,
    borderColor: "#1B365D",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: "#1B365D",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  inputDescripcion: {
    backgroundColor: "#f8efd8",
    borderWidth: 1,
    borderColor: "#1B365D",
    borderRadius: 8,
    height: 100,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: "#1B365D",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  col: {
    flex: 0.48,
  },
  dateButton: {
    backgroundColor: "#f8efd8",
    borderWidth: 1,
    borderColor: "#1B365D",
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
  },
  dateButtonText: {
    color: "#1B365D",
    fontSize: 15,
  },
  button: {
    backgroundColor: "#f4d7a4",
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1B365D",
    alignItems: "center",
    marginTop: 10,
    elevation: 2,
  },
  buttonText: {
    color: "#1B365D",
    fontSize: 16,
    fontWeight: "bold",
  },
  frentesContainer: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#E6DFD3",
  },
  secondaryButton: {
    backgroundColor: "#f7daa9",
    borderWidth: 1,
    borderColor: "#1B365D",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#1B365D",
    fontSize: 15,
    fontWeight: "600",
  },
  carta: {
    flexDirection: "row",
    backgroundColor: "#f8efd8",
    borderWidth: 1,
    borderColor: "#1B365D",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 12,
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  deleteButton: {
    backgroundColor: "#f4d7a4",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1B365D",
  },
  listContent: {
    paddingVertical: 8,
  },
  contratistaCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f8efd8",
    borderWidth: 1,
    borderColor: "#1B365D",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 12,
    marginTop: 8,
  },
  contratistaInfo: {
    flex: 1,
    marginRight: 10,
  },
  contratistaNombre: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1B365D",
  },
  contratistaDetalle: {
    fontSize: 13,
    color: "#456491",
    marginTop: 2,
  },
  contratistaAcciones: {
    flexDirection: "column",
    gap: 6,
  },
  modificarButton: {
    backgroundColor: "#f4d7a4",
    borderWidth: 1,
    borderColor: "#8B1E1E",
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  modificarButtonText: {
    color: "#8B1E1E",
    fontSize: 13,
    fontWeight: "600",
  },
  eliminarButton: {
    backgroundColor: "#8b1e1ea8",
    borderWidth: 1,
    borderColor: "#f4d7a4",
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  eliminarButtonText: {
    color: "#f4d7a4",
    fontSize: 13,
    fontWeight: "600",
  },
  cancelarObraButton: {
    backgroundColor: "#8b1e1ea8",
    borderWidth: 1,
    borderColor: "#8b1e1ea8",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  cancelarObraButtonText: {
    color: "#f4d7a4",
    fontSize: 15,
    fontWeight: "600",
  },
  confirmarObraButton: {
    backgroundColor: "#f4d7a4",
    borderWidth: 1,
    borderColor: "#1B365D",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  confirmarObraButtonText: {
    color: "#1B365D",
    fontSize: 15,
    fontWeight: "600",
  },
  listEmptyText: {
    color: "#1B365D",
    fontSize: 14,
    textAlign: "center",
    marginVertical: 10,
  },
  margintop: {
    marginTop: 8,
  },
  detallesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
  },

  detalle: {
    fontSize: 13,
    color: "#555",
    marginRight: 12,
  },
  infoContainer: {
    flex: 1,
    marginRight: 12,
  },
  containerEmptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  containerCargando: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#94A3B8",
  },
  textEmptyState: {
    color: "rgba(255, 255, 255, 0.60)",
    fontSize: 25,
  },
  center: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  bottonFlotante: {
    position: "absolute",
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    borderColor: "#1B365D",
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8efd8",
    elevation: 5, // Android
    shadowOpacity: 0.3, // iOS
  },
})

export default styles
